-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.usuario
(
    login text NOT NULL,
    nome text NOT NULL,
    data_nascimento date NOT NULL,
    senha text NOT NULL,
    email text NOT NULL,
    telefone text NOT NULL,
    PRIMARY KEY (login)
);

CREATE TABLE public.anuncio
(
    idanuncio serial NOT NULL,
    estilo integer NOT NULL,
    spotify text,
    instrumentos text NOT NULL,
    cache_minimo double precision,
    descricao text NOT NULL,
    foto text NOT NULL,
    usuario_login text NOT NULL,
    PRIMARY KEY (idanuncio)
);

CREATE TABLE public.contrata
(
    anuncio_idanuncio serial NOT NULL,
    usuario_login text NOT NULL,
    id_contrata serial NOT NULL,
    data_contratacao timestamp without time zone NOT NULL,
    cache_combinado double precision NOT NULL,
    local_evento text NOT NULL,
    PRIMARY KEY (id_contrata)
);

ALTER TABLE public.anuncio
    ADD FOREIGN KEY (usuario_login)
    REFERENCES public.usuario (login)
    NOT VALID;


ALTER TABLE public.contrata
    ADD FOREIGN KEY (anuncio_idanuncio)
    REFERENCES public.anuncio (idanuncio)
    NOT VALID;


ALTER TABLE public.contrata
    ADD FOREIGN KEY (usuario_login)
    REFERENCES public.usuario (login)
    NOT VALID;

END;